// Multi2 RTL testbench
// Tests: key schedule, ECB decrypt, CBC decrypt, back-to-back throughput.
// Test vectors loaded from sim/vectors/*.hex (generated by model/gen_vectors.py).
`timescale 1ns/1ps

module multi2_tb;
    // ── Clock & reset ─────────────────────────────────────────────────────────
    reg clk = 0;
    always #5 clk = ~clk;  // 100 MHz

    reg rst_n = 0;
    initial begin
        @(posedge clk); #1;
        @(posedge clk); #1;
        rst_n = 1;
    end

    // ── DUT ───────────────────────────────────────────────────────────────────
    reg         key_valid = 0;
    reg [255:0] sk        = 0;
    reg  [63:0] dk        = 0;
    reg  [63:0] iv_in     = 0;
    reg         blk_valid = 0;
    reg  [63:0] ct_blk    = 0;
    wire        pt_valid;
    wire [63:0] pt_blk;
    wire        busy;

    multi2_cbc_dec #(.N_SUPER(32)) dut (
        .clk(clk), .rst_n(rst_n),
        .key_valid(key_valid), .sk(sk), .dk(dk), .iv(iv_in),
        .blk_valid(blk_valid), .ct_blk(ct_blk),
        .pt_valid(pt_valid), .pt_blk(pt_blk), .busy(busy)
    );

    // ── Test vector storage ───────────────────────────────────────────────────
    // ECB vectors: {key[319:0], pt[63:0], ct[63:0]} = 448 bits = 56 bytes = 112 hex chars
    // Stored as 2 lines: [351:0] key+pt, [63:0] ct
    // Simpler: store as 3 separate arrays
    parameter N_ECB = 8;
    parameter N_CBC_BLK = 18;

    reg [319:0] ecb_key [0:N_ECB-1];
    reg  [63:0] ecb_pt  [0:N_ECB-1];
    reg  [63:0] ecb_ct  [0:N_ECB-1];

    // CBC vectors per block: {key[319:0], iv[63:0], ct[63:0], pt[63:0]}
    reg [319:0] cbc_key [0:N_CBC_BLK-1];
    reg  [63:0] cbc_iv  [0:N_CBC_BLK-1];
    reg  [63:0] cbc_ct  [0:N_CBC_BLK-1];
    reg  [63:0] cbc_pt  [0:N_CBC_BLK-1];

    // ── Counters ──────────────────────────────────────────────────────────────
    integer pass_cnt = 0;
    integer fail_cnt = 0;
    integer i;

    task check;
        input [63:0] got;
        input [63:0] exp;
        input [127:0] label;
        begin
            if (got === exp) begin
                $display("  PASS  %s", label);
                pass_cnt = pass_cnt + 1;
            end else begin
                $display("  FAIL  %s", label);
                $display("        got: %016h", got);
                $display("        exp: %016h", exp);
                fail_cnt = fail_cnt + 1;
            end
        end
    endtask

    // ── Hex file loading ──────────────────────────────────────────────────────
    // Each ECB line is 112 hex chars = 56 bytes. readmemh packs from MSB.
    // We read into a wide register and slice manually.
    reg [447:0] ecb_raw [0:N_ECB-1];   // key(320)+pt(64)+ct(64) = 448b
    reg [511:0] cbc_raw [0:N_CBC_BLK-1]; // key(320)+iv(64)+ct(64)+pt(64)=512b

    // ── Load vectors and run tests ────────────────────────────────────────────
    initial begin
        $dumpfile("sim.vcd");
        $dumpvars(0, multi2_tb);

        // Load hex files
        $readmemh("vectors/ecb_tv.hex",  ecb_raw);
        $readmemh("vectors/cbc_tv.hex",  cbc_raw);

        // Unpack ECB vectors
        for (i = 0; i < N_ECB; i = i + 1) begin
            ecb_key[i] = ecb_raw[i][447:128];
            ecb_pt[i]  = ecb_raw[i][127: 64];
            ecb_ct[i]  = ecb_raw[i][ 63:  0];
        end

        // Unpack CBC vectors
        for (i = 0; i < N_CBC_BLK; i = i + 1) begin
            cbc_key[i] = cbc_raw[i][511:192];
            cbc_iv[i]  = cbc_raw[i][191:128];
            cbc_ct[i]  = cbc_raw[i][127: 64];
            cbc_pt[i]  = cbc_raw[i][ 63:  0];
        end

        // Wait for reset
        @(posedge rst_n);
        repeat(2) @(posedge clk);

        // ── Phase 1: ECB decrypt (drive via CBC module, IV=0, 1 block each) ──
        $display("\n=== Phase 1: ECB-style decrypt (N=32 super-rounds = 128 pi ops) ===");
        for (i = 0; i < N_ECB; i = i + 1) begin
            // Load key: sk=key[319:64], dk=key[63:0], iv=0
            @(posedge clk); #1;
            sk        = ecb_key[i][319:64];
            dk        = ecb_key[i][63:0];
            iv_in     = 64'h0;
            key_valid = 1;
            @(posedge clk); #1;
            key_valid = 0;

            // Wait for key schedule (9+1 cycles safety)
            wait(!busy);
            @(posedge clk); #1;

            // Feed ciphertext block (ECB: IV=0, so CBC output = ECB output)
            ct_blk    = ecb_ct[i];
            blk_valid = 1;
            @(posedge clk); #1;
            blk_valid = 0;

            // Wait for result
            wait(pt_valid);
            @(posedge clk); #1;
            check(pt_blk, ecb_pt[i], "ecb_decrypt");
            @(posedge clk); #1;
        end

        // ── Phase 2: CBC decrypt (sequences of 6 blocks each) ────────────────
        $display("\n=== Phase 2: CBC decrypt (3 sequences x 6 blocks) ===");
        begin : cbc_phase
            integer seq, blk_idx;
            reg [63:0] running_iv;
            reg [319:0] cur_key;

            for (seq = 0; seq < 3; seq = seq + 1) begin
                blk_idx = seq * 6;  // first block of this sequence in cbc_raw

                // Load key+IV from first block of sequence
                @(posedge clk); #1;
                sk        = cbc_key[blk_idx][319:64];
                dk        = cbc_key[blk_idx][63:0];
                iv_in     = cbc_iv[blk_idx];
                key_valid = 1;
                @(posedge clk); #1;
                key_valid = 0;

                wait(!busy);
                @(posedge clk); #1;

                // Feed 6 blocks back-to-back
                begin : blk_loop
                    integer b;
                    for (b = 0; b < 6; b = b + 1) begin
                        ct_blk    = cbc_ct[blk_idx + b];
                        blk_valid = 1;
                        @(posedge clk); #1;
                        blk_valid = 0;

                        wait(pt_valid);
                        @(posedge clk); #1;
                        check(pt_blk, cbc_pt[blk_idx + b], "cbc_decrypt");
                        @(posedge clk); #1;
                    end
                end
            end
        end

        // ── Phase 3: key_valid official test vector (libtomcrypt TV0) ────────
        $display("\n=== Phase 3: libtomcrypt official test vector ===");
        @(posedge clk); #1;
        // key: 32 zeros + 0123456789abcdef; iv=0; ct=f89440845e11cf89; pt=0000000000000001
        sk        = 256'h0;
        dk        = 64'h0123456789abcdef;
        iv_in     = 64'h0;
        key_valid = 1;
        @(posedge clk); #1;
        key_valid = 0;
        wait(!busy);
        @(posedge clk); #1;
        ct_blk    = 64'hf89440845e11cf89;
        blk_valid = 1;
        @(posedge clk); #1;
        blk_valid = 0;
        wait(pt_valid);
        @(posedge clk); #1;
        check(pt_blk, 64'h0000000000000001, "libtomcrypt TV0");

        // ── Summary ───────────────────────────────────────────────────────────
        repeat(4) @(posedge clk);
        $display("\n========================================");
        $display("  TOTAL: %0d passed, %0d failed", pass_cnt, fail_cnt);
        $display("========================================");
        if (fail_cnt == 0) $display("  ALL TESTS PASSED");
        else               $display("  FAILURES DETECTED");
        $finish;
    end

    // Timeout watchdog
    initial begin
        #500000;
        $display("TIMEOUT");
        $finish;
    end
endmodule
